/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c dbusControlDaemon -a dbusControlDaemon.h:dbusControlDaemon.cpp dbusControlDaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSCONTROLDAEMON_H_1327858876
#define DBUSCONTROLDAEMON_H_1327858876

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface gr.oob.startOobProfileDaemon
 */
class dbusControlDaemon: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "gr.oob.startOobProfileDaemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"gr.oob.startOobProfileDaemon\">\n"
"    <method name=\"start\"/>\n"
"    <method name=\"stop\"/>\n"
"    <method name=\"setgpsmode\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"setinterval\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"setradius\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    dbusControlDaemon(QObject *parent);
    virtual ~dbusControlDaemon();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void setgpsmode(const QString &in0);
    void setinterval(const QString &in0);
    void setradius(const QString &in0);
    void start();
    void stop();
Q_SIGNALS: // SIGNALS
};

#endif
