/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c dbusControlDaemon -a dbusControlDaemon.h:dbusControlDaemon.cpp dbusControlDaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusControlDaemon.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class dbusControlDaemon
 */

dbusControlDaemon::dbusControlDaemon(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

dbusControlDaemon::~dbusControlDaemon()
{
    // destructor
}

void dbusControlDaemon::setgpsmode(const QString &in0)
{
    // handle method call gr.oob.startOobProfileDaemon.setgpsmode
    QMetaObject::invokeMethod(parent(), "setgpsmode", Q_ARG(QString, in0));
}

void dbusControlDaemon::setinterval(const QString &in0)
{
    // handle method call gr.oob.startOobProfileDaemon.setinterval
    QMetaObject::invokeMethod(parent(), "setinterval", Q_ARG(QString, in0));
}

void dbusControlDaemon::setradius(const QString &in0)
{
    // handle method call gr.oob.startOobProfileDaemon.setradius
    QMetaObject::invokeMethod(parent(), "setradius", Q_ARG(QString, in0));
}

void dbusControlDaemon::start()
{
    // handle method call gr.oob.startOobProfileDaemon.start
    QMetaObject::invokeMethod(parent(), "start");
}

void dbusControlDaemon::stop()
{
    // handle method call gr.oob.startOobProfileDaemon.stop
    QMetaObject::invokeMethod(parent(), "stop");
}

